name: Dependency Updates

on:
  push:
    branches:
      - main

jobs:
  dependency_updates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      # No need to check updates manually, Dependabot will handle it

  

      - name: Run tests
        run: npm test
