name: Documentation Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # You can specify the Python version that you need for MkDocs.

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs
    - name: Build Docs
      run: mkdocs build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.CI_TOKEN }}
        publish_dir: ./site
